########## 配置项目启动端口号
server:
  port: 11111
spring:
  application:
    name: shc-registry
  ########## 开启 Spring Boot 的 Bean 的 Override 机制
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: localhost
  client:
    ########## 禁止 Eureka Server 将自己的服务注册到注册中心
    register-with-eureka: false
    ########## 禁止本注册中线去其他注册中心发现服务
    fetch-registry: false
    ########## 暴露注册中心地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
